var course = [
	{
		title: "Front End Web Developer",
		skill: "JS, ES6, Node, MongoDB, HTML5, CSS3",
		difficulty: "Intermediate",
		price: 160,
		image: "https://www.udacity.com/assets/iridium/images/school-programming/new/student-ammar.jpg",
	},
	{
		title: "Introduction to Cybersecurity",
		skill: "JS, ES6, Node, MongoDB, HTML5, CSS3",
		difficulty: "Beginner",
		price: 120,
		image: "https://www.udacity.com/assets/iridium/images/school-programming/new/student-ammar.jpg",
	},
	{
		title: "Product Manager",
		skill: "JS, ES6, Node, MongoDB, HTML5, CSS3",
		difficulty: "Advanced",
		price: 170,
		image: "https://www.udacity.com/assets/iridium/images/school-programming/new/student-ammar.jpg",
	},
	{
		title: "Learn Intermediate JavaScript",
		skill: "JS, ES6, Node, MongoDB, HTML5, CSS3",
		difficulty: "Intermediate",
		price: 290,
		image: "https://www.udacity.com/assets/iridium/images/school-programming/new/student-ammar.jpg",
	},
	{
		title: "Learn SQL",
		skill: "JS, ES6, Node, MongoDB, HTML5, CSS3",
		difficulty: "Beginner",
		price: 235,
		image: "https://www.udacity.com/assets/iridium/images/shared/school-of/ai.jpg",
	},
	{
		title: "Object Oriented JavaScript",
		skill: "JS, ES6, Node, MongoDB, HTML5, CSS3",
		difficulty: "Intermediate",
		price: 199,
		image: "https://www.udacity.com/assets/iridium/images/shared/school-of/data_science.jpg",
	},
	{
		title: "The Complete JavaScript Course",
		skill: "JS, ES6, Node, MongoDB, HTML5, CSS3",
		difficulty: "Intermediate",
		price: 215,
		image: "https://www.udacity.com/assets/iridium/images/shared/school-of/programming.jpg",
	},
	{
		title: "Functional Programming",
		skill: "JS, ES6, Node, MongoDB, HTML5, CSS3",
		difficulty: "Beginner",
		price: 220,
		image: "https://www.udacity.com/assets/iridium/images/shared/school-of/ai.jpg",
	},
	{
		title: "Asynchronous Programming in JavaScript",
		skill: "JS, ES6, Node, MongoDB, HTML5, CSS3",
		difficulty: "Intermediate",
		price: 260,
		image: "https://www.udacity.com/assets/iridium/images/shared/school-of/ai.jpg",
	},
	{
		title: "Introduction to SQL",
		skill: "JS, ES6, Node, MongoDB, HTML5, CSS3",
		difficulty: "Advanced",
		price: 160,
		image: "https://www.udacity.com/assets/iridium/images/shared/school-of/ai.jpg",
	},
	{
		title: "Introduction to Python Programming",
		skill: "JS, ES6, Node, MongoDB, HTML5, CSS3",
		difficulty: "Intermediate",
		price: 155,
		image: "https://www.udacity.com/assets/iridium/images/shared/school-of/ai.jpg",
	},
	{
		title: "Introduction to Version Control",
		skill: "JS, ES6, Node, MongoDB, HTML5, CSS3",
		difficulty: "Advanced",
		price: 130,
		image: "https://www.udacity.com/assets/iridium/images/shared/school-of/ai.jpg",
	},
	{
		title: "Applying Data Science to Product Management",
		skill: "JS, ES6, Node, MongoDB, HTML5, CSS3",
		difficulty: "Intermediate",
		price: 245,
		image: "https://www.udacity.com/assets/iridium/images/shared/school-of/ai.jpg",
	},
	{
		title: "Pre-Programming: Everything you need to know before you code",
		skill: "JS, ES6, Node, MongoDB, HTML5, CSS3",
		difficulty: "Intermediate",
		price: 310,
		image: "https://www.udacity.com/assets/iridium/images/shared/school-of/ai.jpg",
	},
	{
		title: "Complete React Developer in 2020 (w/ Redux, Hooks, GraphQL)",
		skill: "JS, ES6, Node, MongoDB, HTML5, CSS3",
		difficulty: "Advanced",
		price: 185,
		image: "https://www.udacity.com/assets/iridium/images/shared/school-of/ai.jpg",
	},
];

export default course;
